import {FormEvent, useEffect, useState} from 'react'
import {Link} from 'react-router-dom'
import {BarChart, Bar, Cell, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis} from 'recharts'
import {ArrowDown, ArrowUp, ClipboardCheck, Download, Search, ShieldCheck} from 'lucide-react'
import {api} from '../api'
import {Badge, ErrorBox, PageTitle} from '../components/UI'
import './executive.css'

const severityColors:Record<string,string>={Critical:'#c74343',High:'#d28b28',Medium:'#3d80aa',Low:'#519387',Informational:'#8492a2',Unknown:'#9a8fa6',Reviewed:'#087f79',Pending:'#d28b28',Skipped:'#8492a2'}
const today=()=>new Date().toISOString().slice(0,10)
const weekAgo=()=>new Date(Date.now()-6*86400000).toISOString().slice(0,10)
const number=(n:number|null|undefined, unit?:string)=>n==null?'No data':unit==='percent'?`${n.toFixed(1)}%`:Number.isInteger(n)?n.toLocaleString():n.toFixed(1)
const short=(name:string)=>name.length>25?name.slice(0,24)+'…':name

function Metric({label,value,detail}:{label:string;value:string;detail?:string}){return <div className="executive-metric"><span>{label}</span><strong>{value}</strong>{detail&&<small>{detail}</small>}</div>}
function Chart({title,description,rows,field='value',percent=false,horizontal=true}:{title:string;description:string;rows:any[];field?:string;percent?:boolean;horizontal?:boolean}){
 const populated=rows.some(row=>row[field]!=null)&&(percent||rows.some(row=>row[field]>0))
 return <section className="panel executive-chart"><h2>{title}</h2><p>{description}</p>{!populated?<div className="executive-no-data">No data in this period and scope</div>:<><div className="executive-chart-canvas" role="img" aria-label={`${title}: ${rows.map(x=>`${x.name} ${number(x[field],percent?'percent':undefined)}`).join(', ')}`}><ResponsiveContainer width="100%" height="100%"><BarChart data={rows} layout={horizontal?'vertical':'horizontal'} margin={{left:0,right:20,top:6,bottom:5}}><CartesianGrid strokeDasharray="3 3" horizontal={!horizontal} vertical={horizontal} stroke="#e6edf0"/>{horizontal?<><XAxis type="number" allowDecimals={percent} domain={percent?[0,100]:[0,'auto']} tickFormatter={x=>percent?`${x}%`:String(x)} axisLine={false} tickLine={false}/><YAxis type="category" dataKey="name" width={125} tickFormatter={short} axisLine={false} tickLine={false}/></>:<><XAxis dataKey="name" tickFormatter={short}/><YAxis domain={percent?[0,100]:[0,'auto']}/></>}<Tooltip formatter={(v:any)=>number(Number(v),percent?'percent':undefined)} cursor={{fill:'#f3f7f8'}}/><Bar dataKey={field} name={percent?'Review coverage':'Findings'} radius={horizontal?[0,5,5,0]:[5,5,0,0]} barSize={20}>{rows.map((row,i)=><Cell key={i} fill={severityColors[row.name]||'#087f79'}/>)}</Bar></BarChart></ResponsiveContainer></div><table className="sr-only"><caption>{title}</caption><thead><tr><th>Category</th><th>Value</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td>{r.name}</td><td>{number(r[field],percent?'percent':undefined)}</td></tr>)}</tbody></table></>}</section>
}
function Trend({rows,field,title}:{rows:any[];field:string;title:string}){return <section className="panel executive-chart"><h2>{title}</h2><p>Saved campaign populations by reporting period</p>{!rows.some(r=>r[field]!=null)?<div className="executive-no-data">No historical campaign data</div>:<div className="executive-chart-canvas"><ResponsiveContainer width="100%" height="100%"><LineChart data={rows} margin={{left:0,right:20,top:5,bottom:5}}><CartesianGrid strokeDasharray="3 3" stroke="#e6edf0"/><XAxis dataKey="period" tickFormatter={x=>String(x).slice(0,10)}/><YAxis domain={field==='review_coverage'?[0,100]:[0,'auto']} allowDecimals={false}/><Tooltip formatter={(v:any)=>number(Number(v),field==='review_coverage'?'percent':undefined)}/><Line type="monotone" dataKey={field} name={field==='review_coverage'?'Review coverage %':field==='risk_exposure'?'Average snapshot residual risk':'Reviewed entries'} stroke="#087f79" strokeWidth={3} dot={{r:4}} connectNulls={false}/></LineChart></ResponsiveContainer></div>}</section>}

export function ExecutiveReport(){
 const [data,setData]=useState<any>(),[error,setError]=useState(''),[loading,setLoading]=useState(false),[campaigns,setCampaigns]=useState<any[]>([])
 const [filters,setFilters]=useState<Record<string,string>>({period_start:weekAgo(),period_end:today(),severity:'',asset_group:'',business_owner:'',it_owner:'',application_owner:'',regulatory:'',campaign_id:''})
 const [applied,setApplied]=useState(filters)
 const query=(values:Record<string,string>)=>new URLSearchParams(Object.fromEntries(Object.entries(values).filter(([,value])=>value))).toString()
 useEffect(()=>{let current=true;setLoading(true);setError('');api('/executive-report?'+query(applied)).then(result=>{if(current)setData(result)}).catch(e=>{if(current)setError(e.message)}).finally(()=>{if(current)setLoading(false)});return()=>{current=false}},[applied])
 useEffect(()=>{api('/review-campaigns?limit=100').then(result=>setCampaigns(result.items||result)).catch(()=>{})},[])
 const change=(key:string,value:string)=>setFilters({...filters,[key]:value})
 function search(event:FormEvent){event.preventDefault();setApplied({...filters})}
 const g=data?.governance?.summary||{}, posture=data?.assessment_posture||{}, breakdowns=data?.governance?.breakdowns||{}, trends=data?.governance?.trends||[]
 const exportQuery=query(applied)
 return <div className="executive-page"><PageTitle title="Executive report" description="An evidence-based view of exposure, assessment posture and vulnerability review governance." actions={<div className="actions"><a className="button primary" href={'/api/executive-report.pdf?'+exportQuery} download><Download size={16}/> Export PDF</a><a className="button" href="/api/review-report.csv?days=7" download>Weekly review CSV</a><button onClick={()=>window.print()}>Print</button></div>}/>
 <ErrorBox error={error}/>
 <form className="panel executive-filters" onSubmit={search}><div className="executive-filter-heading"><h2>Report scope</h2><span className="source"><ShieldCheck size={14}/> {data?.environment||'Session environment'}</span></div><div className="form-grid"><label>Period start<input type="date" value={filters.period_start} max={filters.period_end} onChange={e=>change('period_start',e.target.value)} required/></label><label>Period end<input type="date" value={filters.period_end} min={filters.period_start} onChange={e=>change('period_end',e.target.value)} required/></label><label>Campaign<select value={filters.campaign_id} onChange={e=>change('campaign_id',e.target.value)}><option value="">All campaigns in period</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Technical severity<select value={filters.severity} onChange={e=>change('severity',e.target.value)}><option value="">All severities</option>{Object.keys(severityColors).slice(0,6).map(s=><option key={s}>{s}</option>)}</select></label><label>Business owner<input value={filters.business_owner} onChange={e=>change('business_owner',e.target.value)} placeholder="All business owners"/></label><label>IT remediation owner<input value={filters.it_owner} onChange={e=>change('it_owner',e.target.value)} placeholder="All IT owners"/></label><label>Application owner<input value={filters.application_owner} onChange={e=>change('application_owner',e.target.value)} placeholder="All application owners"/></label><label>Asset group<input value={filters.asset_group} onChange={e=>change('asset_group',e.target.value)} placeholder="All asset groups"/></label><label>Regulatory scope<select value={filters.regulatory} onChange={e=>change('regulatory',e.target.value)}><option value="">All regulatory scopes</option>{['None','PCI DSS','SOC 2','SOX','HIPAA','GDPR','Other'].map(s=><option key={s}>{s}</option>)}</select></label></div><div className="actions"><button className="primary" disabled={loading}><Search size={16}/> {loading?'Loading…':'Apply report filters'}</button><span className="muted">All filters are combined. Exposure is current; governance uses the selected reporting period.</span></div></form>
 {!data&&!error&&<div className="panel loading-card" aria-live="polite">Preparing your report…</div>}
 {data&&<article aria-busy={loading} className={loading?'executive-content executive-refreshing':'executive-content'}>
 <section className="panel executive-position"><div className="section-head"><div><span className="eyebrow">MANAGEMENT BRIEF</span><h2>{data.environment} · {data.period.start} to {data.period.end}</h2><p>Generated {new Date(data.generated_at).toLocaleString()}</p></div><Badge level="Low">{number(data.summary.assessment_coverage,'percent')} assessed</Badge></div><div className="executive-kpis"><Metric label="Active findings" value={number(data.summary.total_findings)}/><Metric label="Critical" value={number(data.severity.Critical)}/><Metric label="High" value={number(data.severity.High)}/><Metric label="Average residual risk" value={number(data.summary.risk_exposure)} detail={`${data.summary.scored_findings} current scored findings`}/><Metric label="Reviewed population entries" value={number(g.reviewed)}/><Metric label="Review coverage" value={number(g.review_coverage,'percent')} detail="Reviewed / frozen population"/><Metric label="Campaign completion" value={number(g.campaign_completion_rate,'percent')}/><Metric label="Overdue campaigns" value={number(g.overdue_campaigns)}/><Metric label="Pending reviews" value={number(g.pending)}/><Metric label="Skipped reviews" value={number(g.skipped)}/><Metric label="Approved exceptions" value={number(data.summary.approved_exceptions)} detail="Unexpired approvals"/><Metric label="Asset inventory coverage" value={number(data.summary.asset_coverage,'percent')}/></div><div className="executive-narrative">{data.narrative.map((sentence:string,i:number)=><p key={i}>{sentence}</p>)}</div><p className="footnote">{data.statement}</p></section>
 <div className="summary-banner"><span><ShieldCheck size={18}/> Risk appetite <Badge>{data.methodology.appetite||'No methodology'}</Badge></span><span>Methodology {data.methodology.version||'n/a'}</span></div>
 <div className="executive-dashboard"><section className="panel"><div className="section-head"><div><h2>Assessment posture</h2><p>Current completed assessments under the current methodology</p></div><ClipboardCheck size={20}/></div><div className="posture"><div><strong className="danger-text">{posture.above_appetite}</strong><span>Above risk appetite</span></div><div><strong className="teal-text">{posture.within_appetite}</strong><span>Within risk appetite</span></div><div><strong>{posture.unassessed}</strong><span>Require assessment</span></div></div><div className="completion"><span>Completed assessments <b>{data.summary.assessed} / {data.summary.total_findings}</b></span><progress value={data.summary.assessed} max={Math.max(1,data.summary.total_findings)}/><span>{posture.draft_assessments} drafts · {posture.stale_assessments} stale · {posture.never_assessed} never assessed</span></div><p className="footnote">Within appetite does not constitute risk acceptance.</p></section><Chart title="Residual risk distribution" description={`${data.summary.assessed} current completed scored findings; stale and draft scores excluded`} rows={Object.entries(posture.residual_distribution||{}).map(([name,value])=>({name,value}))}/></div>
 <div className="executive-grid"><Chart title="Technical exposure" description="Current active findings by scanner technical severity" rows={Object.entries(data.severity).map(([name,value])=>({name,value}))}/><Chart title="Review governance" description="Frozen campaign population entries; skipped is separate from reviewed" rows={['Reviewed','Pending','Skipped'].map(name=>({name,value:g[name.toLowerCase()]}))}/><Trend rows={trends} field="review_coverage" title="Review coverage trend"/><Trend rows={trends} field="reviewed" title="Findings reviewed over time"/><Trend rows={data.governance.risk_trends||[]} field="risk_exposure" title="Campaign snapshot residual risk"/></div>
 <section className="panel table-panel executive-comparisons"><div className="section-head"><div><h2>Period comparison</h2><p>Previous period: {data.period.previous_start} to {data.period.previous_end}. Percent changes are percentage points.</p></div></div><div className="table-scroll"><table><thead><tr><th>Metric</th><th>Current</th><th>Previous</th><th>Change</th><th>Direction</th></tr></thead><tbody>{data.comparisons.map((r:any)=><tr key={r.key}><td>{r.label}</td><td>{number(r.current,r.unit)}</td><td>{r.previous==null?'n/a':number(r.previous,r.unit)}</td><td>{r.change==null?'n/a':<span className={'executive-change '+r.direction}>{r.arrow==='up'?<ArrowUp size={14}/>:r.arrow==='down'?<ArrowDown size={14}/>:null}{r.change>0?'+':''}{r.change.toFixed(1)}{r.unit==='percent'?' pp':''}</span>}</td><td>{r.direction==='n/a'?'No previous population':r.direction}</td></tr>)}</tbody></table></div></section>
 <div className="executive-grid"><Chart title="Review coverage by severity" description="Snapshot severity at campaign activation" rows={breakdowns.severity||[]} field="review_coverage" percent/><Chart title="Review coverage by business owner" description="First 10 owners; full ownership population in PDF" rows={(breakdowns.business_owner||[]).slice(0,10)} field="review_coverage" percent/><Chart title="Review coverage by IT owner" description="First 10 IT remediation owners; snapshot accountability" rows={(breakdowns.it_owner||[]).slice(0,10)} field="review_coverage" percent/><Chart title="Review coverage by asset group" description="First 10 groups; campaign snapshot data" rows={(breakdowns.asset_group||[]).slice(0,10)} field="review_coverage" percent/></div>
 <section className="panel executive-chart"><h2>Campaign completion trend</h2><p>Completed, overdue and other incomplete campaigns by reporting period</p>{trends.length===0?<div className="executive-no-data">No historical campaign data</div>:<div className="executive-chart-canvas"><ResponsiveContainer width="100%" height="100%"><BarChart data={trends}><CartesianGrid strokeDasharray="3 3" stroke="#e6edf0"/><XAxis dataKey="period" tickFormatter={x=>String(x).slice(0,10)}/><YAxis allowDecimals={false}/><Tooltip/><Legend/><Bar dataKey="completed" name="Completed" fill="#087f79" stackId="campaigns"/><Bar dataKey="overdue" name="Overdue" fill="#c74343" stackId="campaigns"/><Bar dataKey="incomplete" name="Other incomplete" fill="#d28b28" stackId="campaigns"/></BarChart></ResponsiveContainer></div>}</section>
 <section className="panel executive-attention"><h2>Management attention required</h2>{data.management_attention.length===0?<p>No documented threshold was triggered. A no-data population does not establish compliance.</p>:<ul>{data.management_attention.map((item:any,i:number)=><li key={i}><Badge level={item.severity}>{item.severity}</Badge><div><p>{item.text}</p><Link to={item.link}>Open supporting population →</Link></div></li>)}</ul>}<details><summary>Attention thresholds</summary><p>Overdue campaigns &gt; 0; critical pending &gt; 0; campaign review coverage &lt; 80%; owner or group coverage &lt; 80% with at least 5 entries; skipped share &gt; 10%; review coverage decline of at least 10 percentage points. Conditions are generated deterministically from data.</p></details></section>
 <section className="panel table-panel"><div className="section-head"><div><h2>Top plugins and risk contributors</h2><p>Current live exposure with saved current scores only</p></div></div><div className="table-scroll"><table><thead><tr><th>Vulnerability / plugin</th><th>Findings</th><th>Critical / High</th><th>Average residual risk</th><th>Pending reviews</th></tr></thead><tbody>{data.top_exposures.map((r:any,i:number)=><tr key={i}><td>{r.name}<small>Plugin {r.plugin_id||'Manual'}</small></td><td>{r.findings}</td><td>{r.critical_high}</td><td>{number(r.risk)}<small>{r.scored} current scored findings</small></td><td>{r.pending_reviews}</td></tr>)}</tbody></table>{!data.top_exposures.length&&<div className="empty">No active findings match this scope.</div>}</div></section>
 <p className="footnote">{data.history_statement} Campaign population entries represent review obligations; the same finding in two campaigns has two review obligations.</p>
 </article>}
 </div>
}
