import {FormEvent,useEffect,useState} from 'react'
import {api,post,User} from '../api'
import {Badge,ErrorBox,PageTitle} from '../components/UI'

export function DataQuality(){
 const [data,setData]=useState<any>(),[error,setError]=useState(''),[message,setMessage]=useState(''),[clearing,setClearing]=useState(false)
 const load=()=>api('/data-quality').then(setData).catch(e=>setError(e.message))
 useEffect(()=>{load()},[])
 async function clearData(){
  if(window.prompt('This permanently clears this environment’s operational vulnerability data. Type CLEAR DATA to continue.')!=='CLEAR DATA')return
  setClearing(true);setError('');setMessage('')
  try{const result=await post('/data-quality/clear-operational-data',{confirmation:'CLEAR DATA'});setMessage(result.message);load()}catch(e){setError((e as Error).message)}finally{setClearing(false)}
 }
 return <><PageTitle title="Data quality" description="Find gaps that make risk results incomplete or misleading."/><ErrorBox error={error}/>{message&&<div className="notice success">{message}</div>}{data&&<><section className="panel table-panel"><div className="section-head"><h2>{data.assets.toLocaleString()} assets · {data.findings.toLocaleString()} findings</h2></div><table><thead><tr><th>Check</th><th>Status</th><th>Affected</th><th>Rate</th><th>Recommended action</th></tr></thead><tbody>{data.checks.map((x:any)=><tr key={x.name}><td><strong>{x.name}</strong></td><td><Badge level={x.status==='Good'?'Low':'High'}>{x.status}</Badge></td><td>{x.count.toLocaleString()}</td><td>{x.percent==null?'—':`${x.percent}%`}</td><td>{x.action}</td></tr>)}</tbody></table></section>{data.can_clear&&<section className="panel"><div className="section-head"><div><h2>Reset operational data</h2><p>Clear findings, assets, imports, assessments, synchronization history, and review campaign snapshots for this environment.</p></div></div><p className="helper">Users, risk methodology, asset rules, Tenable credentials, and the audit history are retained. This cannot run while Tenable synchronization is active.</p><button className="danger" disabled={clearing||data.sync_running} onClick={clearData}>{clearing?'Clearing data…':data.sync_running?'Tenable sync is running':'Clear operational data'}</button></section>}</>}</>
}

export function Exceptions({user}:{user:User}){
 const [items,setItems]=useState<any[]>([]),[error,setError]=useState(''),[message,setMessage]=useState('');const load=()=>api('/exceptions').then(setItems).catch(e=>setError(e.message));useEffect(()=>{load()},[])
 async function decide(id:number,status:string){try{await api(`/exceptions/${id}`,{method:'PUT',body:JSON.stringify({status})});load()}catch(e){setError((e as Error).message)}}
 async function request(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await post(`/findings/${f.get('finding_id')}/exceptions`,{justification:f.get('justification'),evidence:f.get('evidence'),expires_at:new Date(String(f.get('expires_at'))+'T23:59:59Z').toISOString(),review_frequency_days:Number(f.get('review_frequency_days'))});e.currentTarget.reset();setMessage('Exception submitted for administrator review.');load()}catch(e){setError((e as Error).message)}}
 return <><PageTitle title="Risk exceptions" description="Time-bound risk decisions with justification, evidence, approval, and expiration."/><ErrorBox error={error}/>{message&&<div className="notice success">{message}</div>}{user.role!=='Viewer'&&<form className="panel" onSubmit={request}><h2>Request an exception</h2><div className="form-grid"><label>Finding ID<input name="finding_id" type="number" min="1" required/></label><label>Expiration date<input name="expires_at" type="date" required/></label><label>Review frequency (days)<input name="review_frequency_days" type="number" min="1" max="365" defaultValue="90" required/></label><label className="wide">Business justification<textarea name="justification" minLength={10} required/></label><label className="wide">Evidence references<textarea name="evidence"/></label></div><button className="primary">Submit for approval</button></form>}<section className="panel table-panel"><table><thead><tr><th>Finding</th><th>Decision record</th><th>Expires</th><th>Status</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><strong>{x.finding}</strong><small>{x.asset} · Finding {x.finding_id}</small></td><td>{x.justification}<small>{x.evidence||'No evidence reference'} · Requested by {x.requested_by}</small></td><td>{new Date(x.expires_at).toLocaleDateString()}<small>Review every {x.review_frequency_days} days</small></td><td><Badge level={x.status==='Approved'?'Low':x.status==='Expired'?'Critical':'Medium'}>{x.status}</Badge></td><td>{user.role==='Administrator'&&x.status==='Requested'&&<div className="actions"><button onClick={()=>decide(x.id,'Approved')}>Approve</button><button onClick={()=>decide(x.id,'Rejected')}>Reject</button></div>}</td></tr>)}</tbody></table></section></>
}

export function Controls({user}:{user:User}){
 const [items,setItems]=useState<any[]>([]),[owners,setOwners]=useState<any[]>([]),[error,setError]=useState(''),[message,setMessage]=useState('');const load=()=>api('/controls').then(setItems).catch(e=>setError(e.message));useEffect(()=>{load();api('/owners').then(setOwners)},[])
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await post('/controls',{name:f.get('name'),description:f.get('description'),owner_id:f.get('owner_id')?Number(f.get('owner_id')):null,evidence_requirements:f.get('evidence_requirements'),mappings:{NIST:String(f.get('nist')||'').split(',').map(x=>x.trim()).filter(Boolean),CIS:String(f.get('cis')||'').split(',').map(x=>x.trim()).filter(Boolean)},design_maturity:f.get('design_maturity')?Number(f.get('design_maturity')):null,operating_effectiveness:f.get('operating_effectiveness')?Number(f.get('operating_effectiveness')):null,active:true});e.currentTarget.reset();setMessage('Control added to the reusable library.');load()}catch(e){setError((e as Error).message)}}
 return <><PageTitle title="Control library" description="Reusable control definitions, owners, evidence expectations, maturity, and framework mappings."/><ErrorBox error={error}/>{message&&<div className="notice success">{message}</div>}<div className="management-grid"><section className="panel table-panel"><table><thead><tr><th>Control</th><th>Owner</th><th>Maturity</th><th>Mappings</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><strong>{x.name}</strong><small>{x.description}</small></td><td>{x.owner||'Unassigned'}</td><td>{x.design_maturity||'—'} / {x.operating_effectiveness||'—'}</td><td>{Object.entries(x.mappings||{}).flatMap(([k,v]:any)=>v.map((n:string)=>`${k} ${n}`)).join(', ')||'—'}</td></tr>)}</tbody></table></section>{user.role==='Administrator'&&<form className="panel" onSubmit={create}><h2>Add control</h2><label>Name<input name="name" required/></label><label>Description<textarea name="description"/></label><label>Owner<select name="owner_id"><option value="">Unassigned</option>{owners.map(x=><option value={x.id} key={x.id}>{x.username}</option>)}</select></label><label>Evidence requirements<textarea name="evidence_requirements"/></label><div className="form-grid"><label>Design maturity<input name="design_maturity" type="number" min="1" max="5"/></label><label>Operating effectiveness<input name="operating_effectiveness" type="number" min="1" max="5"/></label><label>NIST mappings<input name="nist" placeholder="PR.AC-5, DE.CM-1"/></label><label>CIS mappings<input name="cis" placeholder="12.2, 13.3"/></label></div><button className="primary full">Add control</button></form>}</div></>
}

export {ExecutiveReport} from './ExecutiveReport'
