import { FormEvent, useEffect, useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { Plus, ArrowRight, ArrowLeft, Search, CalendarDays, Filter, Check, ShieldCheck, BarChart3, Archive, ListFilter } from 'lucide-react'
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid, LineChart, Line, PieChart, Pie, Cell, Legend } from 'recharts'
import { api, post, User } from '../api'
import { ErrorBox, PageTitle } from '../components/UI'
import { Breakdown, Campaign, CampaignBadge, CampaignDialog, CampaignEmpty, CampaignLoading, CampaignPagination, Coverage, Due, Metrics, Reviewer, ReviewIdentityNote, Scope, ScopeChips, ScopeFields, cleanScope, date, percent } from '../components/campaignShared'
import '../campaigns.css'

type Analytics = { summary: Metrics & { active_campaigns: number; completed_campaigns: number; overdue_campaigns: number; due_soon_campaigns: number; average_review_coverage: number | null; campaign_completion_rate: number | null }; campaigns: Campaign[]; trends: Array<{ period: string; reviewed: number; review_coverage: number | null; completed: number; overdue: number; incomplete: number }>; breakdowns: Record<string, Breakdown[]> }
type Saved = { id: number; name: string; filters: Scope }
type Preview = { total: number; items: Array<{ id: number; name?: string; plugin_id?: string; asset?: { hostname?: string; ip?: string } | string; severity?: string; technical?: { severity?: string } }> }
const chartColors = ['#168a80', '#6da5d0', '#e5a14a', '#d97784']
const analyticsKeys = ['severity', 'business_owner', 'it_owner', 'application_owner', 'asset_group', 'asset_tag', 'regulatory', 'period_start', 'period_end', 'campaign_id']
const analyticsScopeFromUrl = (search: string) => Object.fromEntries([...new URLSearchParams(search)].filter(([key]) => analyticsKeys.includes(key)))
const tooltipStyle = { borderRadius: 12, border: '1px solid #dce8ed', boxShadow: '0 8px 24px #233e4a14', fontSize: 12 }

export default function ReviewCampaigns({ user }: { user: User }) {
  const location = useLocation()
  const initialScope = analyticsScopeFromUrl(location.search)
  const [analyticsScope, setAnalyticsScope] = useState<Scope>(initialScope)
  const [overdueOnly, setOverdueOnly] = useState(new URLSearchParams(location.search).get('overdue') === 'true')
  const [sort, setSort] = useState('id:desc')
  const [tab, setTab] = useState<'campaigns' | 'analytics' | 'history'>(Object.keys(initialScope).length ? 'analytics' : 'campaigns')
  const [analytics, setAnalytics] = useState<Analytics>(), [rows, setRows] = useState<Campaign[]>([]), [total, setTotal] = useState(0)
  const [filters, setFilters] = useState({ q: '', status: '' }), [draftFilters, setDraftFilters] = useState({ q: '', status: '' }), [offset, setOffset] = useState(0)
  const [loading, setLoading] = useState(true), [error, setError] = useState(''), [create, setCreate] = useState(false), [refresh, setRefresh] = useState(0)
  const [ownerDimension, setOwnerDimension] = useState('business_owner')
  useEffect(() => {
    const scoped = analyticsScopeFromUrl(location.search); setAnalyticsScope(scoped); setOverdueOnly(new URLSearchParams(location.search).get('overdue') === 'true'); if (Object.keys(scoped).length) setTab('analytics'); setOffset(0)
  }, [location.search])
  useEffect(() => {
    const controller = new AbortController()
    api<Analytics>('/review-campaigns/analytics?' + new URLSearchParams(analyticsScope), { signal: controller.signal }).then(setAnalytics).catch(err => { if (err.name !== 'AbortError') setError(err.message) })
    return () => controller.abort()
  }, [refresh, analyticsScope])
  useEffect(() => {
    const controller = new AbortController(); setLoading(true)
    api<{ items: Campaign[]; total: number }>('/review-campaigns?' + new URLSearchParams({ ...filters, overdue: overdueOnly ? 'true' : 'false', sort: sort.split(':')[0], direction: sort.split(':')[1], history: tab === 'history' ? 'true' : 'false', limit: '25', offset: String(offset) }), { signal: controller.signal }).then(data => { setRows(data.items); setTotal(data.total); setError('') }).catch(err => { if (err.name !== 'AbortError') setError(err.message) }).finally(() => { if (!controller.signal.aborted) setLoading(false) })
    return () => controller.abort()
  }, [filters, offset, tab, refresh, overdueOnly, sort])
  const summary = analytics?.summary
  function search(event: FormEvent) { event.preventDefault(); setFilters({ ...draftFilters }); setOffset(0) }
  function switchTab(value: typeof tab) { setTab(value); setOffset(0); setFilters({ q: '', status: '' }); setDraftFilters({ q: '', status: '' }) }
  return <div className="campaign-page"><PageTitle eyebrow="REVIEW GOVERNANCE" title="Review campaigns" description="A clear record of who reviewed each vulnerability, when, and with what outcome." actions={user.role !== 'Viewer' && <button className="primary" onClick={() => setCreate(true)}><Plus size={17} />Create campaign</button>} />
    <div className="campaign-context"><ShieldCheck size={18} /><div><strong>{user.environment} review workspace</strong><span>Campaigns preserve the population and asset context recorded at activation.</span></div><Link to="/reports/executive">Executive report <ArrowRight size={14} /></Link></div>
    <ErrorBox error={error} />
    {(Object.keys(analyticsScope).length > 0 || overdueOnly) && <div className="campaign-active-scope"><div><strong>{overdueOnly ? 'Overdue campaign population' : 'Filtered review population'}</strong><ScopeChips scope={analyticsScope} /></div><button className="text-button" onClick={() => { setAnalyticsScope({}); setOverdueOnly(false); window.history.replaceState(null, '', location.pathname) }}>Clear report filters</button></div>}
    <div className="campaign-kpis">{[
      ['Active campaigns', summary?.active_campaigns, 'Reviews in progress', 'teal'], ['Completed campaigns', summary?.completed_campaigns, 'Documented review cycles', 'blue'], ['Overdue campaigns', summary?.overdue_campaigns, 'Past the review due date', 'red'],
      ['Average review coverage', summary ? percent(summary.average_review_coverage) : undefined, 'Reviewed / snapshot population', 'teal'], ['Awaiting review', summary?.pending, 'Pending campaign review records', 'amber'], ['Due soon', summary?.due_soon_campaigns, 'Due within the next 7 days', 'blue'],
    ].map(([title, value, description, tone]) => <div className={`campaign-kpi ${tone}`} key={String(title)}><span>{title}</span><strong>{value == null ? '—' : typeof value === 'number' ? value.toLocaleString() : value}</strong><small>{description}</small></div>)}</div>
    <div className="campaign-tabs" role="tablist" aria-label="Review campaign views">{([['campaigns', 'Campaigns', ListFilter], ['analytics', 'Analytics', BarChart3], ['history', 'Completed & archived', Archive]] as const).map(([value, label, Icon]) => <button role="tab" aria-selected={tab === value} id={`campaign-tab-${value}`} aria-controls={`campaign-panel-${value}`} className={tab === value ? 'active' : ''} key={value} onClick={() => switchTab(value)}><Icon size={16} />{label}</button>)}</div>
    <div role="tabpanel" aria-labelledby={`campaign-tab-${tab}`} id={`campaign-panel-${tab}`}>
      {tab === 'analytics' ? analytics ? <div className="campaign-chart-grid">
        <ChartPanel title="Review coverage by campaign" description="Reviewed findings as a share of each activation snapshot." empty={!analytics.campaigns.length}><ResponsiveContainer width="100%" height="100%"><BarChart data={analytics.campaigns.filter(campaign => campaign.status !== 'Draft').slice(0, 12).map(campaign => ({ name: campaign.name, coverage: campaign.metrics.review_coverage }))}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e8eef2" /><XAxis dataKey="name" tickFormatter={truncate} tick={{ fontSize: 10 }} /><YAxis domain={[0, 100]} tickFormatter={value => `${value}%`} tick={{ fontSize: 10 }} /><Tooltip contentStyle={tooltipStyle} formatter={value => [percent(value as number), 'Review coverage']} /><Bar dataKey="coverage" fill="#168a80" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></ChartPanel>
        <ChartPanel title="Coverage trend" description="Snapshot review coverage by reporting period." empty={!analytics.trends.length}><ResponsiveContainer width="100%" height="100%"><LineChart data={analytics.trends}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e8eef2" /><XAxis dataKey="period" tick={{ fontSize: 10 }} /><YAxis domain={[0, 100]} tickFormatter={value => `${value}%`} tick={{ fontSize: 10 }} /><Tooltip contentStyle={tooltipStyle} formatter={value => [percent(value as number), 'Review coverage']} /><Line type="monotone" dataKey="review_coverage" stroke="#168a80" strokeWidth={3} dot={{ r: 4 }} connectNulls={false} /></LineChart></ResponsiveContainer></ChartPanel>
        <ChartPanel title="Review status" description="Skipped findings are shown separately from reviewed findings." empty={!summary?.total}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={[{ name: 'Reviewed', value: summary?.reviewed || 0 }, { name: 'Pending', value: summary?.pending || 0 }, { name: 'Skipped', value: summary?.skipped || 0 }]} dataKey="value" nameKey="name" innerRadius={58} outerRadius={88} paddingAngle={3}>{chartColors.slice(0, 3).map(color => <Cell key={color} fill={color} />)}</Pie><Tooltip contentStyle={tooltipStyle} /><Legend wrapperStyle={{ fontSize: 11 }} /></PieChart></ResponsiveContainer></ChartPanel>
        <BreakdownChart title="Coverage by severity" description="Technical severity at activation." rows={analytics.breakdowns.severity || []} />
        <BreakdownChart title="Coverage by owner" description="Accountability follows the asset ownership recorded in the snapshot." rows={analytics.breakdowns[ownerDimension] || []} horizontal actions={<select aria-label="Owner coverage dimension" value={ownerDimension} onChange={event => setOwnerDimension(event.target.value)}><option value="business_owner">Business owner</option><option value="it_owner">IT remediation owner</option><option value="application_owner">Application owner</option></select>} />
        <BreakdownChart title="Coverage by asset group" description="Review gaps across the business estate." rows={analytics.breakdowns.asset_group || []} />
        <ChartPanel title="Campaign completion trend" description="Completed, overdue, and incomplete campaigns by period." empty={!analytics.trends.length}><ResponsiveContainer width="100%" height="100%"><BarChart data={analytics.trends}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e8eef2" /><XAxis dataKey="period" tick={{ fontSize: 10 }} /><YAxis allowDecimals={false} tick={{ fontSize: 10 }} /><Tooltip contentStyle={tooltipStyle} /><Legend wrapperStyle={{ fontSize: 11 }} /><Bar dataKey="completed" name="Completed" fill="#168a80" radius={[4, 4, 0, 0]} /><Bar dataKey="overdue" name="Overdue" fill="#d97784" radius={[4, 4, 0, 0]} /><Bar dataKey="incomplete" name="Incomplete" fill="#6da5d0" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></ChartPanel>
        <ChartPanel title="Campaign status" description="The state of activated review cycles in this population." empty={!analytics.campaigns.length}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={Object.entries(analytics.campaigns.reduce<Record<string, number>>((counts, campaign) => ({ ...counts, [campaign.status]: (counts[campaign.status] || 0) + 1 }), {})).map(([name, value]) => ({ name, value }))} dataKey="value" nameKey="name" innerRadius={58} outerRadius={88} paddingAngle={3}>{['#168a80', '#6da5d0', '#e5a14a', '#a38dbb', '#72b8ae'].map(color => <Cell key={color} fill={color} />)}</Pie><Tooltip contentStyle={tooltipStyle} /><Legend wrapperStyle={{ fontSize: 11 }} /></PieChart></ResponsiveContainer></ChartPanel>
        <div className="campaign-metrics-definition"><ShieldCheck size={18} /><div><strong>Review coverage {percent(summary?.review_coverage)} · Processed coverage {percent(summary?.processed_coverage)}</strong><p>Review coverage counts documented review decisions. Processed coverage includes reviewed and skipped findings. Counts represent campaign review records; a finding may participate in several periods.</p></div></div>
        {Object.keys(analyticsScope).length > 0 && <section className="panel campaign-analytics-population"><div className="section-head"><div><h2>Supporting campaign population</h2><p>Open a campaign to review the matching historical findings.</p></div></div><div className="table-scroll"><table><thead><tr><th>Campaign</th><th>Total entries</th><th>Reviewed</th><th>Pending</th><th>Coverage</th><th></th></tr></thead><tbody>{analytics.campaigns.filter(c => c.metrics.total > 0).map(c => <tr key={c.id}><td>{c.name}</td><td>{c.metrics.total}</td><td>{c.metrics.reviewed}</td><td>{c.metrics.pending}</td><td>{percent(c.metrics.review_coverage)}</td><td><Link className="button" to={`/review-campaigns/${c.id}?${new URLSearchParams({ ...cleanScope(analyticsScope), status: 'Pending' })}`}>Open pending findings <ArrowRight size={14} /></Link></td></tr>)}</tbody></table>{!analytics.campaigns.some(c => c.metrics.total > 0) && <CampaignEmpty title="No matching campaign entries">Adjust the report filters to see review evidence.</CampaignEmpty>}</div></section>}
      </div> : <CampaignLoading>Loading review analytics…</CampaignLoading> : <section className="panel campaign-table-panel">
        <form className="campaign-filter-bar" onSubmit={search}><label className="campaign-search"><Search size={16} /><input aria-label="Search campaigns" placeholder="Search campaign name…" value={draftFilters.q} onChange={event => setDraftFilters({ ...draftFilters, q: event.target.value })} /></label><select aria-label="Campaign status" value={draftFilters.status} onChange={event => setDraftFilters({ ...draftFilters, status: event.target.value })}><option value="">{tab === 'history' ? 'Completed & archived' : 'All statuses'}</option>{(tab === 'history' ? ['Completed', 'Archived'] : ['Draft', 'Active', 'In Progress', 'Completed', 'Reopened', 'Archived']).map(status => <option key={status}>{status}</option>)}</select><select aria-label="Sort campaigns" value={sort} onChange={event => { setSort(event.target.value); setOffset(0) }}><option value="id:desc">Newest first</option><option value="name:asc">Name A–Z</option><option value="due_date:asc">Earliest due date</option><option value="period_start:desc">Latest reporting period</option></select><button type="submit" className="primary"><Filter size={15} />Search</button><button type="button" className="text-button" onClick={() => { setDraftFilters({ q: '', status: '' }); setFilters({ q: '', status: '' }); setOverdueOnly(false); setOffset(0) }}>Clear</button></form>
        {loading ? <CampaignLoading /> : rows.length ? <><div className="table-scroll"><table className="campaign-list"><thead><tr><th>Campaign & reporting period</th><th>Status</th><th>Review coverage</th><th>Reviewers</th><th>Schedule</th><th><span className="sr-only">Open campaign</span></th></tr></thead><tbody>{rows.map(campaign => <tr key={campaign.id}><td><Link className="campaign-name" to={`/review-campaigns/${campaign.id}`}>{campaign.name}</Link><small>{date(campaign.period_start)} – {date(campaign.period_end)} · {campaign.frequency}</small><span className="campaign-scope-summary">{Object.keys(cleanScope(campaign.scope)).length ? `${Object.keys(cleanScope(campaign.scope)).length} scope filters` : 'All findings'} · {campaign.metrics.total.toLocaleString()} findings</span></td><td><CampaignBadge status={campaign.status} overdue={campaign.overdue} /></td><td><Coverage metrics={campaign.metrics} compact /></td><td><div className="campaign-reviewer-stack">{campaign.reviewers.slice(0, 3).map(reviewer => <span title={reviewer.username} key={reviewer.id}>{reviewer.username.slice(0, 2).toUpperCase()}</span>)}{campaign.reviewers.length > 3 && <span>+{campaign.reviewers.length - 3}</span>}</div><small>{campaign.reviewers.length ? campaign.reviewers.map(reviewer => reviewer.username).join(', ') : 'Not assigned'}</small></td><td><Due campaign={campaign} /><small>Due {date(campaign.due_date)}</small></td><td><Link className="campaign-open" aria-label={`Open ${campaign.name}`} to={`/review-campaigns/${campaign.id}`}><ArrowRight size={17} /></Link></td></tr>)}</tbody></table></div><CampaignPagination total={total} offset={offset} limit={25} onChange={setOffset} /></> : <CampaignEmpty title={tab === 'history' ? 'No completed campaigns yet' : 'Start a consistent review cycle'} action={user.role !== 'Viewer' && <button className="primary" onClick={() => setCreate(true)}><Plus size={16} />Create campaign</button>}>{filters.q || filters.status ? 'No campaigns match your filters.' : tab === 'history' ? 'Completed review cycles and their evidence will appear here.' : user.role === 'Viewer' ? 'Completed campaign results will become available here.' : 'Define a population, assign reviewers, and preserve the evidence for this reporting period.'}</CampaignEmpty>}
      </section>}
    </div>
    {create && <CampaignWizard user={user} onClose={() => setCreate(false)} onCreated={() => { setRefresh(value => value + 1); setCreate(false) }} />}
  </div>
}

function truncate(value: unknown) { const text = String(value); return text.length > 16 ? text.slice(0, 15) + '…' : text }
function ChartPanel({ title, description, children, empty = false, actions }: { title: string; description: string; children: React.ReactNode; empty?: boolean; actions?: React.ReactNode }) {
  return <section className="panel campaign-chart-panel"><div className="section-head"><div><h2>{title}</h2><p>{description}</p></div>{actions}</div><div className="campaign-chart">{empty ? <div className="campaign-chart-empty">No review data for this view</div> : children}</div></section>
}
function BreakdownChart({ title, description, rows, horizontal = false, actions }: { title: string; description: string; rows: Breakdown[]; horizontal?: boolean; actions?: React.ReactNode }) {
  return <ChartPanel title={title} description={description} empty={!rows.length} actions={actions}><ResponsiveContainer width="100%" height="100%"><BarChart data={rows.slice(0, 8)} layout={horizontal ? 'vertical' : 'horizontal'} margin={{ left: 0, right: 12, bottom: 0 }}>{horizontal ? <><XAxis type="number" domain={[0, 100]} tickFormatter={value => `${value}%`} tick={{ fontSize: 10 }} /><YAxis type="category" dataKey="name" width={105} tickFormatter={truncate} tick={{ fontSize: 10 }} /></> : <><XAxis dataKey="name" tickFormatter={truncate} tick={{ fontSize: 10 }} /><YAxis domain={[0, 100]} tickFormatter={value => `${value}%`} tick={{ fontSize: 10 }} /></>}<Tooltip contentStyle={tooltipStyle} formatter={value => [percent(value as number), 'Review coverage']} /><Bar dataKey="review_coverage" fill="#6da5d0" radius={horizontal ? [0, 5, 5, 0] : [5, 5, 0, 0]} barSize={26} /></BarChart></ResponsiveContainer></ChartPanel>
}

function CampaignWizard({ user, onClose, onCreated }: { user: User; onClose: () => void; onCreated: () => void }) {
  const navigate = useNavigate(), today = new Date().toISOString().slice(0, 10)
  const [step, setStep] = useState(0), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  const [details, setDetails] = useState({ name: '', description: '', frequency: 'weekly', period_start: today, period_end: today, start_date: today, due_date: today })
  const [scope, setScope] = useState<Scope>({}), [saved, setSaved] = useState<Saved[]>([]), [savedId, setSavedId] = useState('')
  const [reviewers, setReviewers] = useState<Reviewer[]>([]), [reviewerIds, setReviewerIds] = useState<number[]>([user.id])
  const [preview, setPreview] = useState<Preview>(), [previewLoading, setPreviewLoading] = useState(true)
  const [launchAcknowledged, setLaunchAcknowledged] = useState(false)
  const steps = ['Details', 'Scope', 'Preview', 'Reviewers', 'Schedule', 'Review & launch']
  useEffect(() => { const controller = new AbortController(); Promise.all([api<Saved[]>('/saved-filters', { signal: controller.signal }), api<Reviewer[]>('/review-campaigns/reviewers', { signal: controller.signal })]).then(([views, people]) => { setSaved(views); setReviewers(people); setReviewerIds(ids => ids.filter(id => people.some(person => person.id === id))) }).catch(err => { if (err.name !== 'AbortError') setError(err.message) }); return () => controller.abort() }, [])
  useEffect(() => { const controller = new AbortController(); setPreviewLoading(true); setPreview(undefined); const timer = setTimeout(() => api<Preview>('/review-campaigns/preview', { method: 'POST', body: JSON.stringify({ scope: cleanScope(scope) }), signal: controller.signal }).then(data => { setPreview(data); setError('') }).catch(err => { if (err.name !== 'AbortError') setError(err.message) }).finally(() => { if (!controller.signal.aborted) setPreviewLoading(false) }), 350); return () => { clearTimeout(timer); controller.abort() } }, [scope])
  function next() {
    setError('')
    if (step === 0 && !details.name.trim()) { setError('Enter a campaign name.'); return }
    if (step === 3 && !reviewerIds.length) { setError('Assign at least one reviewer.'); return }
    if (step === 4 && (!details.period_start || !details.period_end || !details.start_date || !details.due_date || details.period_start > details.period_end || details.start_date > details.due_date)) { setError('Choose a valid reporting period and a due date on or after the start date.'); return }
    setStep(value => value + 1)
  }
  async function save(activate: boolean) {
    if (activate && (!launchAcknowledged || !preview?.total || previewLoading)) return
    setBusy(true); setError('')
    let created: Campaign | undefined
    try {
      created = await post<Campaign>('/review-campaigns', { ...details, name: details.name.trim(), description: details.description.trim(), scope: cleanScope(scope), reviewer_ids: reviewerIds })
      if (activate) await post(`/review-campaigns/${created.id}/activate`, {})
      onCreated(); navigate(`/review-campaigns/${created.id}`)
    } catch (err) {
      if (created) { onCreated(); navigate(`/review-campaigns/${created.id}`, { state: { campaignError: `Draft saved. Activation failed: ${(err as Error).message}` } }) }
      else setError((err as Error).message)
    } finally { setBusy(false) }
  }
  return <CampaignDialog title="Create review campaign" description="Set the scope once. Keep the review evidence for every period." onClose={onClose} busy={busy} wide>
    <ol className="campaign-wizard-steps">{steps.map((label, index) => <li key={label} className={index === step ? 'active' : index < step ? 'done' : ''} aria-current={index === step ? 'step' : undefined}><span>{index < step ? <Check size={12} /> : index + 1}</span><b>{label}</b></li>)}</ol>
    <ErrorBox error={error} />
    <div className="campaign-wizard-body">
      {step === 0 && <><div className="campaign-step-heading"><span>01 / CAMPAIGN DETAILS</span><h3>Give this review cycle a clear purpose</h3><p>Use a name your team and management will recognize in exported evidence.</p></div><label>Campaign name *<input required maxLength={200} placeholder="Weekly critical vulnerability review" value={details.name} onChange={event => setDetails({ ...details, name: event.target.value })} autoFocus /></label><label>Purpose and review instructions<textarea rows={4} maxLength={5000} placeholder="What should reviewers validate and document?" value={details.description} onChange={event => setDetails({ ...details, description: event.target.value })} /></label><label>Review frequency<select value={details.frequency} onChange={event => setDetails({ ...details, frequency: event.target.value })}><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="one-time">One-time</option></select></label><p className="campaign-helper"><CalendarDays size={15} />After completion, clone this campaign for the next period with a new snapshot.</p></>}
      {step === 1 && <><div className="campaign-step-heading"><span>02 / SCOPE</span><h3>Choose the population to review</h3><p>All selected conditions must match. An empty scope includes every finding in {user.environment}.</p></div><label>Start from a saved finding filter<select value={savedId} onChange={event => { setSavedId(event.target.value); const view = saved.find(item => item.id === Number(event.target.value)); if (view) setScope(view.filters) }}><option value="">Custom scope</option>{saved.map(view => <option key={view.id} value={view.id}>{view.name}</option>)}</select></label><ScopeFields scope={scope} onChange={value => { setScope(value); setSavedId('') }} /><div className="campaign-live-preview" role="status"><Filter size={17} /><strong>{previewLoading ? 'Checking scope…' : preview ? `${preview.total.toLocaleString()} findings match this scope` : 'Preview unavailable'}</strong><span>AND across all filters</span></div></>}
      {step === 2 && <><div className="campaign-step-heading"><span>03 / POPULATION PREVIEW</span><h3>Validate the campaign scope</h3><p>The final population is frozen when you activate the campaign.</p></div><ScopeChips scope={scope} />{previewLoading ? <CampaignLoading>Finding matching vulnerabilities…</CampaignLoading> : preview ? <><div className="campaign-preview-count"><strong>{preview.total.toLocaleString()}</strong><span>matching findings in {user.environment}</span></div>{preview.items.length ? <div className="table-scroll"><table><thead><tr><th>Sample finding</th><th>Plugin</th><th>Asset</th><th>Severity</th></tr></thead><tbody>{preview.items.map(item => <tr key={item.id}><td>{item.name || `Finding ${item.id}`}</td><td>{item.plugin_id || '—'}</td><td>{typeof item.asset === 'string' ? item.asset : item.asset?.hostname || '—'}</td><td>{item.severity || item.technical?.severity || '—'}</td></tr>)}</tbody></table><small>Showing up to 10 examples. All {preview.total.toLocaleString()} matching findings will enter the snapshot.</small></div> : <div className="notice warning">No findings match. Adjust the scope to launch, or save this campaign as a draft.</div>}</> : <div className="notice warning">The population preview is unavailable. Check the scope before activation.</div>}</>}
      {step === 3 && <><div className="campaign-step-heading"><span>04 / REVIEWERS</span><h3>Assign the people recording review decisions</h3><p>Every reviewed or skipped finding records the authenticated reviewer and timestamp.</p></div><ReviewIdentityNote /><div className="campaign-reviewer-options">{reviewers.map(reviewer => <label key={reviewer.id} className={reviewerIds.includes(reviewer.id) ? 'selected' : ''}><input type="checkbox" checked={reviewerIds.includes(reviewer.id)} onChange={event => setReviewerIds(ids => event.target.checked ? [...ids, reviewer.id] : ids.filter(id => id !== reviewer.id))} /><span className="campaign-reviewer-avatar">{reviewer.username.slice(0, 2).toUpperCase()}</span><span><strong>{reviewer.username}</strong><small>{reviewer.role}</small></span></label>)}</div>{!reviewers.length && <CampaignEmpty title="No eligible reviewers">An administrator must enable at least one analyst or administrator account.</CampaignEmpty>}</>}
      {step === 4 && <><div className="campaign-step-heading"><span>05 / SCHEDULE</span><h3>Set a reporting period and review window</h3><p>The review due date tracks this campaign's governance cycle.</p></div><div className="form-grid"><label>Reporting period begins *<input type="date" required value={details.period_start} onChange={event => setDetails({ ...details, period_start: event.target.value })} /></label><label>Reporting period ends *<input type="date" required min={details.period_start} value={details.period_end} onChange={event => setDetails({ ...details, period_end: event.target.value })} /></label><label>Review start date *<input type="date" required value={details.start_date} onChange={event => setDetails({ ...details, start_date: event.target.value })} /></label><label>Review due date *<input type="date" required min={details.start_date} value={details.due_date} onChange={event => setDetails({ ...details, due_date: event.target.value })} /></label></div><div className="campaign-info">Overdue is derived from the review due date while a campaign remains incomplete. Completing the campaign closes this review period.</div></>}
      {step === 5 && <><div className="campaign-step-heading"><span>06 / REVIEW & LAUNCH</span><h3>{details.name}</h3><p>{details.description || 'Review campaign ready to configure.'}</p></div><div className="campaign-launch-summary"><div><span>Environment</span><strong>{user.environment}</strong></div><div><span>Frequency</span><strong>{details.frequency}</strong></div><div><span>Reporting period</span><strong>{date(details.period_start)} – {date(details.period_end)}</strong></div><div><span>Review due date</span><strong>{date(details.due_date)}</strong></div><div><span>Reviewers</span><strong>{reviewers.filter(reviewer => reviewerIds.includes(reviewer.id)).map(reviewer => reviewer.username).join(', ') || 'None assigned'}</strong></div><div><span>Current matching population</span><strong>{previewLoading ? 'Checking…' : preview?.total.toLocaleString() || '0'} findings</strong></div></div><ScopeChips scope={scope} /><label className="campaign-confirm-check"><input type="checkbox" checked={launchAcknowledged} onChange={event => setLaunchAcknowledged(event.target.checked)} /><span>I confirm this scope and reviewer assignment. Activation will freeze the matching population and its asset context for this campaign.</span></label>{(!preview?.total || !reviewerIds.length) && <div className="notice warning">Activation requires at least one matching finding and one reviewer. You can save a draft and complete setup later.</div>}</>}
    </div>
    <div className="campaign-wizard-footer"><button type="button" disabled={busy} onClick={step ? () => setStep(value => value - 1) : onClose}><ArrowLeft size={15} />{step ? 'Back' : 'Cancel'}</button><span>Step {step + 1} of {steps.length}</span><div className="actions">{step === 5 ? <><button disabled={busy || !details.name.trim()} onClick={() => save(false)}>Save draft</button><button className="primary" disabled={busy || previewLoading || !preview?.total || !reviewerIds.length || !launchAcknowledged} onClick={() => save(true)}>{busy ? 'Launching…' : 'Activate campaign'}<ArrowRight size={15} /></button></> : <button className="primary" disabled={busy || (step === 2 && previewLoading)} onClick={next}>Continue<ArrowRight size={15} /></button>}</div></div>
  </CampaignDialog>
}
