import { FormEvent, useEffect, useState, ComponentType } from 'react'
import { NavLink, Navigate, Route, Routes, useLocation } from 'react-router-dom'
import { ShieldCheck, LayoutDashboard, Bug, ClipboardCheck, Server, Upload, Plug, SlidersHorizontal, History, Users, LogOut, Menu, Database, Library, FileText, ShieldAlert } from 'lucide-react'
import { api, post, User } from './api'
import { ErrorBox } from './components/UI'
import Dashboard from './pages/Dashboard'
import Findings from './pages/Findings'
import AssessmentGroups from './pages/AssessmentGroups'
import Workbench from './pages/Workbench'
import Imports from './pages/Imports'
import { Assets, AuditHistory, Administration, MethodologyPage, Tenable } from './pages/Management'
import { DataQuality, Exceptions, Controls, ExecutiveReport } from './pages/Governance'

export default function App(){
 const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[menu,setMenu]=useState(false),[environment,setEnvironment]=useState<'Demo'|'Production'>('Demo')
 const location=useLocation()
 useEffect(()=>{api<User>('/auth/me').then(setUser).catch(()=>{}).finally(()=>setLoading(false))},[])
 useEffect(()=>setMenu(false),[location.pathname])
 async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const form=new FormData(e.currentTarget);try{setUser(await post('/auth/login',{...Object.fromEntries(form),environment}))}catch(e){setError((e as Error).message)}}
 if(loading)return <div className="loading">Loading risk workspace…</div>
 if(!user)return <div className="login"><div className="login-story"><ShieldCheck size={40}/><div className="eyebrow">VRAP / SECURITY OPERATIONS</div><h1>Technical findings.<br/>Business context.<br/><em>Defensible decisions.</em></h1><p>Vulnerability Risk Assessment Platform</p></div><form className="login-form" onSubmit={login}><div className="eyebrow">ANALYST WORKSPACE</div><h2>Choose your environment</h2><div className="environment-picker"><button type="button" className={environment==='Demo'?'environment-card selected':'environment-card'} onClick={()=>setEnvironment('Demo')}><strong>Demo</strong><small>Synthetic findings and guided examples</small></button><button type="button" className={environment==='Production'?'environment-card selected':'environment-card'} onClick={()=>setEnvironment('Production')}><strong>Production</strong><small>Operational findings and integrations</small></button></div><p>Sign in with your administrator-provided account.</p><ErrorBox error={error}/><label>Username<input name="username" autoComplete="username" required autoFocus/></label><label>Password<input name="password" type="password" autoComplete="current-password" required/></label><button className="primary" type="submit">Enter {environment}</button><small>Demo and Production data are separated by the server-side session.</small></form></div>
 const links:Array<[string,string,ComponentType<{size?:number}>]>=[['/','Dashboard',LayoutDashboard],['/findings','Vulnerabilities',Bug],['/assessments','Assessments',ClipboardCheck],['/assets','Assets',Server],['/exceptions','Risk Exceptions',ShieldAlert],['/controls','Control Library',Library],['/data-quality','Data Quality',Database],['/reports/executive','Executive Report',FileText],...(user.role!=='Viewer'?([['/imports','Imports',Upload]] as [string,string,typeof Upload][]):[]),...(user.role==='Administrator'?([['/tenable','Tenable Integration',Plug]] as [string,string,typeof Plug][]):[]),['/methodology','Risk Methodology',SlidersHorizontal],['/audit','Audit History',History],...(user.role==='Administrator'?([['/administration','Administration',Users]] as [string,string,typeof Users][]):[])]
 return <div className="app"><aside className={menu?'sidebar open':'sidebar'}><div className="brand"><span className="brand-icon"><ShieldCheck size={25}/></span><div>VRAP<small>RISK OPERATIONS</small></div></div><div className="workspace-badge">{user.environment} environment</div><div className="nav-label">WORKSPACE</div><nav>{links.map(([path,title,Icon])=><NavLink key={String(path)} to={String(path)} end={path==='/' }><Icon size={18}/>{String(title)}</NavLink>)}</nav><div className="sidebar-bottom"><div className="policy-note">CONTEXT MATTERS<p>Technical severity is the starting point. Your assessment determines organizational risk.</p></div><div className="account"><span className="avatar">{user.username.slice(0,2).toUpperCase()}</span><div><strong>{user.username}</strong><small>{user.role}</small></div><button title="Sign out" onClick={async()=>{try{await post('/auth/logout',{});setUser(null)}catch(e){setError((e as Error).message)}}}><LogOut size={17}/></button></div></div></aside><div className="workspace"><header className="topbar"><button className="mobile-menu" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation"><Menu/></button><span>Security operations <span className="slash">/</span> Vulnerability risk</span><span className="environment">{user.environment.toUpperCase()} · PROVISIONAL METHODOLOGY</span></header><main><Routes><Route path="/" element={<Dashboard/>}/><Route path="/findings" element={<Findings user={user}/>}/><Route path="/assessments" element={<AssessmentGroups user={user}/>}/><Route path="/findings/:id" element={<Workbench user={user}/>}/><Route path="/assets" element={<Assets user={user}/>}/><Route path="/exceptions" element={<Exceptions user={user}/>}/><Route path="/controls" element={<Controls user={user}/>}/><Route path="/data-quality" element={<DataQuality/>}/><Route path="/reports/executive" element={<ExecutiveReport/>}/><Route path="/imports" element={user.role!=='Viewer'?<Imports/>:<Navigate to="/"/>}/><Route path="/tenable" element={user.role==='Administrator'?<Tenable/>:<Navigate to="/"/>}/><Route path="/methodology" element={<MethodologyPage user={user}/>}/><Route path="/audit" element={<AuditHistory/>}/><Route path="/administration" element={user.role==='Administrator'?<Administration/>:<Navigate to="/"/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes></main></div></div>
}
